version: '3'
services:
  app:
    container_name: http-api
    build:
      context: ./http-api
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: nest
      DATABASE_USER: # DATABASE_USER
      DATABASE_PASS: # DATABASE_PASS
      DATABASE_URI: mongodb://mongodbApp:27017
    ports:
      - '4000:4000'
    depends_on:
      - user-microservice
      - todo-microservice
      - mongodbApp
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
  user-microservice:
    container_name: user-microservice
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: nest
      DATABASE_USER: # DATABASE_USER
      DATABASE_PASS: # DATABASE_PASS
      DATABASE_URI: mongodb://mongodbApp:27017
      REDIS_HOST: redisApp
    ports:
      - '4001:4001'
    depends_on:
      - redisApp
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
  todo-microservice:
    container_name: todo-microservice
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: nest
      DATABASE_USER: # DATABASE_USER
      DATABASE_PASS: # DATABASE_PASS
      DATABASE_URI: mongodb://mongodbApp:27017
      REDIS_HOST:  redisApp
    ports:
      - '4002:4002'
    depends_on:
      - redisApp
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
  redisApp:
    image: 'redis:alpine'
    container_name: redis-microservice
    tty: true
    restart: always
    environment:
      -  ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'
    command:
      - redis-server
      - '--bind'
      - redisApp
      - '--port'
      - '6379'
    ports:
      - '6379:6379'
    networks:
      - node-network
  # start the mongodb service as container
  mongodbApp:
    image: mongo:6.0
    container_name: mongodbApp
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - node-network
    logging:
      driver: none

volumes:
  dbdata6:
  mongodb:
  redis_data:
    driver: local

networks:
  redis-net:
    driver: bridge
  node-network:
    driver: bridge