# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.9'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: nest
      DATABASE_USER: # DATABASE_USER
      DATABASE_PASS: # DATABASE_PASS
      DATABASE_URI: mongodb://mongodb:27017
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app
    networks:
      - node-network

  # start the mongodb service as container
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - node-network
    logging:
      driver: none

volumes:
  dbdata6:
  mongodb:

networks:
  node-network:
    driver: bridge